include_guard(GLOBAL)

function(target_enable_python target_name)
    if(ENABLE_PYTHON_PLUGINS)
        find_package(Python COMPONENTS Interpreter Development)
        if(Python_FOUND)
            target_include_directories(${target_name} PUBLIC ${Python_INCLUDE_DIRS})
            # Link to python library on all platforms, not just Windows
            if(TARGET Python::Python)
                target_link_libraries(${target_name} PUBLIC Python::Python)
            else()
                target_link_libraries(${target_name} PUBLIC ${Python_LIBRARIES})
            endif()
        else()
            message(WARNING "Python not found. Disabling Python plugin support.")
            set(ENABLE_PYTHON_PLUGINS OFF)
        endif()
    endif()
endfunction()

function(enable_python)
    if(ENABLE_PYTHON_PLUGINS)
        find_package(Python COMPONENTS Interpreter Development)
        if(Python_FOUND)
            message(STATUS "Python found: ${Python_VERSION}")
            message(STATUS "Python executable: ${Python_EXECUTABLE}")
            message(STATUS "Python include dirs: ${Python_INCLUDE_DIRS}")
            message(STATUS "Python libraries: ${Python_LIBRARIES}")
            
            # Link to python library for the main executable on all platforms
            if(TARGET Python::Python)
                target_link_libraries(mcp-server++ PRIVATE Python::Python)
            else()
                target_link_libraries(mcp-server++ PRIVATE ${Python_LIBRARIES})
            endif()
        else()
            message(WARNING "Python not found. Disabling Python plugin support.")
            set(ENABLE_PYTHON_PLUGINS OFF)
        endif()
    endif()
endfunction()