name: Package

on:
  push:
    branches: [main, master]
    tags: ["v*"]
  pull_request:
    branches: [main, master]

jobs:
  package:
    name: Package for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, windows-2022]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake rpm dpkg
        timeout-minutes: 5

      - name: Install NSIS (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install nsis
        timeout-minutes: 5

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release --log-level=VERBOSE
        timeout-minutes: 10

      - name: Build
        run: |
          cmake --build build --config Release --verbose
        timeout-minutes: 20

      - name: Package (with libs)
        run: |
          cd build
          cpack
        timeout-minutes: 10

      - name: List generated packages (with libs)
        run: |
          ls -la build/
        shell: bash

      - name: Upload artifacts (with libs)
        uses: actions/upload-artifact@v4
        with:
          name: mcp-server++-${{ matrix.os }}-with-libs
          path: |
            build/*.tar.gz
            build/*.zip
            build/*.deb
            build/*.rpm
            build/*.exe

  package-no-libs:
    name: Package for ${{ matrix.os }} (no libs)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, windows-2022]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake rpm dpkg
        timeout-minutes: 5

      - name: Install NSIS (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install nsis
        timeout-minutes: 5

      - name: Configure CMake (no libs)
        run: |
          cmake -B build-nolibs -DCMAKE_BUILD_TYPE=Release -DCPACK_INCLUDE_LIBS=OFF --log-level=VERBOSE
        timeout-minutes: 10

      - name: Build (no libs)
        run: |
          cmake --build build-nolibs --config Release --verbose
        timeout-minutes: 20

      - name: Package (no libs)
        run: |
          cd build-nolibs
          cpack
        timeout-minutes: 10

      - name: List generated packages (no libs)
        run: |
          ls -la build-nolibs/
        shell: bash

      - name: Upload artifacts (no libs)
        uses: actions/upload-artifact@v4
        with:
          name: mcp-server++-${{ matrix.os }}-no-libs
          path: |
            build-nolibs/*.tar.gz
            build-nolibs/*.zip
            build-nolibs/*.deb
            build-nolibs/*.rpm
            build-nolibs/*.exe

  release:
    name: Create Release
    needs: [package, package-no-libs]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mcp-server++-*/*.tar.gz
            mcp-server++-*/*.zip
            mcp-server++-*/*.deb
            mcp-server++-*/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}